name: Build Apex Exe

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller --clean --noconsole --onefile --name "Apex" --icon="assets/apex.ico" --add-data "assets;assets" --strip main.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Apex-Exe
          path: dist/Apex.exe